services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres_fast_api
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: my_super_password
      POSTGRES_DB: fast_api
      PGDATA: /var/lib/postgresql/data/pgdata/
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  fastapi-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app/example.env
    depends_on:
      - postgres
    ports:
      - "8000:8000"

volumes:
  pgdata:
    driver: local